FROM centos:latest
ENV PATH="/root/.local/bin:${PATH}"
RUN yum install python3 python3-pip wget -y
RUN pip3 install -U --user greynoise
RUN pip3 install -U --user shodan
RUN mkdir /storage && mkdir /scripts
RUN cd /scripts && wget https://raw.github.com/securitysavage/savageCTI/main/shodan-ip-download.py && wget https://raw.github.com/securitysavage/savageCTI/main/shodan-parse.py